# -*- coding: utf-8 -*-
"""Assignment_5_AI1103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LmC0Y09CxrIf5Abeyj3JR7EBCfkY_-9v
"""

import random as rand

a = 2 # Let us fix a=2, since a>0

simulations = 1000000

i = 0
sum = 0

while (i < simulations):
  X = rand.uniform(0,20)
  k=0
  while (k<=10):
    if (k*a <= X < (k+1)*a):
      Y = k;
      if (4<Y<5): sum+=1
    k+=1
  i+=1

Pr=sum/simulations

print("By simulation, the value of Pr(4<Y<5) = ",Pr,"\n")
print("By claculation, the value of Pr(4<Y<5) = 0\n")
print("Therefore, the result obtained by the simulations is equal to the value got by calculation\n")